name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_SECRET }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build & Push Backend
        run: |
                docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mern-backend:latest ./mern/backend
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mern-backend:latest

      - name: Build & Push Frontend
        run: |
                docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mern-frontend:latest ./mern/frontend
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mern-frontend:latest

