name: Deploy to GKE

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true           # Add this to authenticate subsequent gcloud/kubectl commands

      - name: Configure kubectl with GKE credentials
        run: |
          gcloud container clusters get-credentials mern-cluster --region=europe-west2 --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f mern/kubernetes/ #path to the k8s files
