on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # STEP 1: Authenticate with service account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # STEP 2: Setup gcloud CLI after auth
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      #  Optional debug check
      - name: Who am I (debug)
        run: gcloud auth list

      # STEP 3: Configure kubeconfig with GKE credentials
      - name: Configure kubectl with GKE credentials
        run: |
          gcloud container clusters get-credentials mern-cluster \
            --region=europe-west2 \
            --project=${{ secrets.GCP_PROJECT_ID }}

      # STEP 4: Deploy to cluster
      - name: Deploy to Kubernetes
        run: kubectl apply -f mern/kubernetes/
