on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # STEP 1: Authenticate with service account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # STEP 2: Setup gcloud CLI after auth
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      # STEP 3: debug check
      - name: Who am I (debug)
        run: gcloud auth list

      # STEP 4: Create GKE Cluster
      - name: Create GKE Cluster
        run: |
          gcloud container clusters describe mern-cluster --region=europe-west2 \
          || gcloud container clusters create mern-cluster \
               --region=europe-west2 \
               --num-nodes=1 \
               --disk-type=pd-standard \
               --disk-size=50 \
               --enable-ip-alias

      # STEP 5: Configure kubeconfig with GKE credentials
      - name: Configure kubectl with GKE credentials
        run: |
          gcloud container clusters get-credentials mern-cluster \
            --region=europe-west2 \
            --project=${{ secrets.GCP_PROJECT_ID }}
      
      # STEP 6: INSTALL GKE auth plugin
      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin -q

      # STEP 7: Deploy to cluster
      - name: Deploy to Kubernetes
        run: kubectl apply -f mern/kubernetes/
